#Welcome to Numpy

In [1]:
import numpy as np
import sys

In [2]:
my_arr = np.array([[3,6,45,67]], np.int64)
#my_arr=> prints array([3,6,45,67])
print(my_arr[0,1])  #prints (0,1)th index, for 2D list []-1D-list 
#print(my_arr)=> prints in form of 1 x 4 matrix
print(my_arr.shape)
print(my_arr.dtype)
my_arr.dtype
my_arr[0,1]=45  #mutable
print(my_arr)

6
(1, 4)
int64
[[ 3 45 45 67]]


#numpy array creation methods

In [3]:
listarr = np.array([[1,2,3],[4,5,6],[69,70,80]])
print(listarr)
print(listarr.shape)
print(listarr.size)
print(listarr.dtype)

[[ 1  2  3]
 [ 4  5  6]
 [69 70 80]]
(3, 3)
9
int32


In [4]:
np.array({34,56,78})
#dtype object is not efficient in mathematical operations
#hence no lists or tuples are reqd

array({56, 34, 78}, dtype=object)

In [5]:
zs= np.zeros((2,5))
print(zs.shape)
print(zs)
print(zs.size)

(2, 5)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
10


In [6]:
rng = np.arange(15)
print(rng)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


#Linear spacing ap {start, end, number of terms}

In [7]:
lspaced = np.linspace(1,50,10)
print(lspaced)

[ 1.          6.44444444 11.88888889 17.33333333 22.77777778 28.22222222
 33.66666667 39.11111111 44.55555556 50.        ]


#empty method

In [8]:
emparr = np.empty((4,6))
print(emparr)
emp_liked = np.empty_like(lspaced)
print(emp_liked)

[[8.86579630e-312 7.65801751e-322 0.00000000e+000 0.00000000e+000
  1.89146896e-307 1.16096346e-028]
 [9.82205649e+252 1.11789342e+253 3.44371413e-086 6.01347002e-154
  3.21867035e-057 3.45688606e-086]
 [4.66452680e-033 4.66726139e-062 3.65874797e-086 6.82247702e-038
  6.74930052e-067 1.99708888e-062]
 [1.51979061e-047 9.72385253e-072 1.28977971e-057 2.21420214e-052
  6.03395543e-154 8.46781366e+136]]
[ 1.          6.44444444 11.88888889 17.33333333 22.77777778 28.22222222
 33.66666667 39.11111111 44.55555556 50.        ]


In [9]:
ide = np.identity(45)
print(ide)
print(ide.shape)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
(45, 45)


In [10]:
arr = np.arange(99).reshape(3,33)   #3 rows + 33 cols, same as arr=arr.reshape()
print(arr)
   #multiply to give arange() value
arr = arr.ravel() #method to reshape to 1D matrix
print(arr.shape)
#print(arr)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56
  57 58 59 60 61 62 63 64 65]
 [66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89
  90 91 92 93 94 95 96 97 98]]
(99,)


In [11]:
#axis0,axis1=row,cols
#sum(axis0)=[12 8 9]; 1D arr= only axis0
#sum(axis1)=[]

x=[[1,2,3],[4,5,6],[7,8,9]]
ar = np.array(x)
print(ar)
print(ar.sum(axis=0), ar.sum(axis=1))   #colwise sum
print(ar.T) #transpose

#ar.flat iterator
#print(ar.flat)=> returns a flat iterator object
'''for item in ar.flat:
    print(item)'''#all elements printed
print(ar.ndim)  #2 cause 2D array
print(ar.size)
print(ar.nbytes)

#all of these are properties not methods, hence no parentheses are used

one = np.array([1,3,64,4,2])
print(one.argmax())     #method hence parentheses were passed

#argmax gives index where maximum element is present
print(one.argmin())

#argsort() returns an indexarray in which if elements were present, then the array would've been sorted
print(one.argsort())

#argmax(axis=) prints the index-axis-wise such that the index printed contains the greatest element in that axis
print(one.argmax(axis=0)) 

#same applies for argsort() and argmin()
print(one.argmin(axis=0))
print(one.argsort(axis=0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[12 15 18] [ 6 15 24]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
2
9
36
2
0
[0 4 1 3 2]
2
0
[0 4 1 3 2]


In [12]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
ar.reshape((9,))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
ar2 = np.array([[1,2,0],[3,2,4],[4,1,2]])
print(ar+ar2)
print(ar*ar2)

print(np.sqrt(ar))  #element-wise sqrt()

print(ar.sum())
print(ar.max())
print(ar.min()) #all of these functions return numbers in array not indices

[[ 2  4  3]
 [ 7  7 10]
 [11  9 11]]
[[ 1  4  0]
 [12 10 24]
 [28  8 18]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]
45
9
1


In [15]:
ar.reshape((3,3))
print(np.where(ar>5))
print(np.count_nonzero(ar))
print(np.nonzero(ar))   #these return indices

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))
9
(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64), array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))


In [16]:
py_array = [0, 4, 34, 56, 78, 91, 23, 11]
np_array = np.array(py_array)
print(sys.getsizeof(1)*len(py_array))
print(np_array.itemsize*np_array.size)

224
32
